name: test_each_pull_request

on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run xcodebuild test 
      run: make test
    - name: Upload codecov
      run: |
        bash <(curl -s https://codecov.io/bash) -J '^UserDefaultsGeneratorCore$' \
          -D .build/derivedData
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}



